include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_NAMESPACE/ci-cd/gradle@0.3
    inputs:
      image: amazoncorretto:21
      publish: branch-pattern
      publish-branch-pattern: "(master|v2r)"
      publish-task: publishAllPublicationsToGitLabRepository